### ISSUE TITLE
Update binaries pls

### ISSUE THREAD

**Issue by vushu** [Kode/Krom_bin#2]
When trying to use krom binaries:
`Krom uses API version 1 but Kha targets API version 2. Please update Krom.`

**Comment by RobDangerous** [comment]
I will eventually. Meanwhile though Krom includes very easy to follow build instructions.

**Comment by vushu** [comment]
I cant locate the release variable inside the korefile.js, I am not sure what to do

also when trying to build the current master with 
node Kore/make --compiler clang --compile
I get:
```
../../Sources/main.cpp:1890:29: error: no member named 'getPixels' in 'Kore::Graphics4::Texture'
                Kore::u8* data = texture->getPixels();
                                 ~~~~~~~  ^

```

**Comment by RobDangerous** [comment]
Update the Kore submodule and just forget about the release var (see https://github.com/Kode/ChakraCore/commit/c81b84779a132f5f310b28f2082ac178d5067caf).

**Comment by vushu** [comment]
Thank you, that did the trick, took a while to compile :)
made a fork with linux binary:
https://github.com/vushu/Krom_bin
